columns:
  age: int
  children: int
  bmi: float
  expenses: float
  sex: category
  smoker: category
  region: category
  

numerical_columns:
  - age
  - bmi
  - children
  - expenses
 
categorical_columns:
  - sex
  - smoker
  - region

target_column: expenses

domain_value:
  sex:
    - male
    - female
  smoker:
    - yes
    - no  
  region:
    - southwest
    - southeast
    - northwest
    - northeast  



  



